// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB98cEhsapgByaP7PguNDBKTRUO3kt2ci4',
    appId: '1:367769070548:web:e83c7b892555826286c441',
    messagingSenderId: '367769070548',
    projectId: 'linebuster-1st-draft',
    authDomain: 'linebuster-1st-draft.firebaseapp.com',
    storageBucket: 'linebuster-1st-draft.appspot.com',
    measurementId: 'G-GCNW6JXPLT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXxOipiAr9Dibm91VfwMhJ85xebTNVrVU',
    appId: '1:367769070548:android:014df8514438783886c441',
    messagingSenderId: '367769070548',
    projectId: 'linebuster-1st-draft',
    storageBucket: 'linebuster-1st-draft.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbqPYLf_3hgY8YafOzoOW54Uv0PBhe0WM',
    appId: '1:367769070548:ios:cba02fb5831e15a986c441',
    messagingSenderId: '367769070548',
    projectId: 'linebuster-1st-draft',
    storageBucket: 'linebuster-1st-draft.appspot.com',
    iosBundleId: 'com.example.linebuster1stDraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbqPYLf_3hgY8YafOzoOW54Uv0PBhe0WM',
    appId: '1:367769070548:ios:cba02fb5831e15a986c441',
    messagingSenderId: '367769070548',
    projectId: 'linebuster-1st-draft',
    storageBucket: 'linebuster-1st-draft.appspot.com',
    iosBundleId: 'com.example.linebuster1stDraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB98cEhsapgByaP7PguNDBKTRUO3kt2ci4',
    appId: '1:367769070548:web:5e05e88afe723e3886c441',
    messagingSenderId: '367769070548',
    projectId: 'linebuster-1st-draft',
    authDomain: 'linebuster-1st-draft.firebaseapp.com',
    storageBucket: 'linebuster-1st-draft.appspot.com',
    measurementId: 'G-G0ZG7EFLKZ',
  );
}
